services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - TUSTENA_API_KEY
      - FLOAT_API_KEY
      - FLOAT_ICAL_URL
    volumes:
      - ~/Downloads:/root/Downloads:ro
      - ./mappings:/mappings
